# fly.toml app configuration file generated for app-1-nodejs-wispy-meadow-9917 on 2024-10-07T15:08:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-1-nodejs-wispy-meadow-9917'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
